site_name: Guia Steam Translation Brasil
site_description: Guia de tradução da equipe brasileira do Steam Translation
site_author: Equipe STS Brasil
site_url: http://sts.berna.zone
repo_url: https://github.com/Berna-L/documentacao-sts-brasil
repo_name: 'Contribua!'
pages:
  - Início: 'index.md'
  - Candidatos:
      - 'Informações gerais': 'candidatos/index.md'
      - Dicas: 'candidatos/dicas.md'
      - Regras: 'candidatos/regras.md'
  - Jogos:
      - Artifact: 'jogos/artifact.md'
      - Dota 2:
        - 'Informações gerais': 'jogos/dota2/index.md'
        - 'Glossário': 'jogos/dota2/glossario.md'
  - Apêndice:
      - Produtos disponíveis: 'apendice/produtos-disponiveis.md'
theme:
  name: 'material'
  language: 'pt'
  font:
    text: 'PT Sans'
  palette:
    primary: 'blue grey'
  logo:
    icon: 'flagflagflag'
extra:
  social:
  - type: 'globe'
    link: https://translation.steampowered.com
  - type: 'steam'
    link: 'https://steamcommunity.com/groups/STSBrasil'